### ISSUE TITLE
Failed to open the homepage

### ISSUE THREAD

**Issue by jackalcooper** [gdotdesign/elm-ui-examples#3]
```
Error: ENOENT: no such file or directory, open '/Users/jackalcooper/Documents/GitHub/elm-ui-examples/public/index.html'
      at Error (native)
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.readFileSync (fs.js:431:33)
      at module.exports (/usr/local/lib/node_modules/elm-ui/bin/lib/render/html.js:4:13)
      at Object.<anonymous> (/usr/local/lib/node_modules/elm-ui/bin/lib/command/serve.js:60:17)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/elm-ui/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/elm-ui/node_modules/co/index.js:54:5
      at new Promise (/usr/local/lib/node_modules/elm-ui/node_modules/core-js/modules/es6.promise.js:191:7)
      at Object.co (/usr/local/lib/node_modules/elm-ui/node_modules/co/index.js:50:10)
```

**Comment by gdotdesign** [comment]
I'm assuming that you are running the `elm-ui start` command in the root directory of this repository.

As it's stated in the readme each example is self contained so in order to run for example the `file-upload` you will need to do the following:

```
cd file-upload
elm-ui install
elm-ui server
```

Please not that these examples haven't been updated to the latest version of Elm-UI, they are working with the `0.3.0`  version which you can install via npm `npm install elm-ui@0.3.0 -g`.

**Comment by jackalcooper** [comment]
Thanks a lot!
